global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: development

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'rules/*.yml'

storage:
  tsdb:
    retention:
      time: '15d'
      size: '5GB'