name: API CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'src/api/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'src/api/**'

env:
  CI: true
  NODE_ENV: test

jobs:
  build-and-test:
    name: Build and Test API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/api

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint
      # Requirement addressed: Code Quality
      # Location: Technical Specification/7.1.2 Security Testing

    - name: Run tests
      run: npm test
      # Requirement addressed: Automated Testing
      # Location: Technical Specification/3.5 CI/CD PIPELINE

    - name: Build application
      run: npm run build
      # Requirement addressed: Build Verification
      # Location: Technical Specification/5.5 CI/CD PIPELINE

    - name: Upload test coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: src/api/coverage

    - name: Build Docker image
      run: |
        docker build -t femtosense/api:${{ github.sha }} .
        docker save femtosense/api:${{ github.sha }} > image.tar
      # Requirement addressed: Build Verification
      # Location: Technical Specification/5.5 CI/CD PIPELINE

    - name: Upload Docker image
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: src/api/image.tar

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true